### ISSUE TITLE
Passthrough invite and cid parameters through to Google Play

### ISSUE THREAD

**Issue by jarradh** [status-im/universal-links-handler#31] opened 2020-03-09 05:33 UTC
Needs to be able to accept urls such as 
https://join.status.im/0x000...?invite=f79989f679386be7aa56dc1c4&cid=foo
and append to google play urls as
https://play.google.com/store/apps/details?id=im.status.ethereum&referrer=out%3D0x000...%26invite%3Df79989f679386be7aa56dc1c4%26cid%3Dfoo

**Comment by jakubgs** [comment] 2020-03-17 12:02
Related notes:

>`out` is the post-onboarding action to perform (same as universal link)
>`invite` is the invite code (needs to be sent in `/event` postback and `/validate`)
>`cid` is clickid for advertising networks (needs to be sent in `/event` postback `/validate`)
>https://notes.status.im/oz6JEr_PTc-WL-WXFKd1OQ

**Comment by jakubgs** [comment] 2020-03-17 12:09
Just to verify:

* The `out` field should contain __exactly__ what is the path after `/` in the URL.
* The `invite` will be set by the Status app when generating the URL, and is based on user key.
* The `cid` will be also set by Status app but will be less dynamic than `invite`.

Correct?

I assume `invite` and `cid` are not directly related to one another and could show up separately.
In those cases should they be sent to Play Store separately as URL args or skipped unless together?

**Comment by jakubgs** [comment] 2020-03-17 13:31
Also, do you want format validation for `invite` and `cid`? I assume the former is a 25 character long hexadecimal while the latter is an alpha-numeric word. Any length limits on `cid`?

And if they are invalid, what should be done? Ignored?

**Comment by jakubgs** [comment] 2020-03-17 14:18
I have it pretty much implemented but the redirect doesn't seem to work. I tried:
```js
window.location = 'market://details?id=im.status.ethereum'
```
and
```js
window.location = 'https://play.google.com/store/apps/details?id=im.status.ethereum'
```
And both do nothing. But this does work:
```js
window.location = 'https://play.app.goo.gl/?link=https://play.google.com/store/apps/details?id=im.status.ethereum'
```
That might be a problem for the `referrer` argument, but I doubt it.

**Comment by jakubgs** [comment] 2020-03-17 14:24
It seems like it might be a problem. Because this link:
https://play.app.goo.gl/?link=https://play.google.com/store/apps/details?id=im.status.ethereum&referrer=out%3Djakubgs.eth%26invite%3Df79989f679386be7aa56dc1c4%26cid%3Dfoo
Redirects to:
https://play.google.com/store/apps/details?id=im.status.ethereum
And drops the `referrer` argument.

**Comment by jakubgs** [comment] 2020-03-17 14:27
But calling `encodeURIComponent()` on the `link` value of `https://play.app.goo.gl/?link=` fixes it:
https://play.app.goo.gl/?link=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dim.status.ethereum%26referrer%3Dout%253Djakubgs.eth%2526invite%253Df79989f679386be7aa56dc1c4%2526cid%253Dfoo
Redirects to:
https://play.google.com/store/apps/details?id=im.status.ethereum&referrer=out%3Djakubgs.eth%26invite%3Df79989f679386be7aa56dc1c4%26cid%3Dfoo

**Comment by jakubgs** [comment] 2020-03-17 14:38
The frustrating thing is that using:
```js
window.locations = status-im://user/jakubgs.eth
```
Doesn't work. There's no effect on Android. Which means that even if someone has Status installed they will still be redirected to the Play Store after `N` seconds, which makes no sense.

**Comment by jakubgs** [comment] 2020-03-18 11:09
According to this:

>However, note that Chrome on Android has a different URL format than the standard Android browser:
>https://developer.chrome.com/multidevice/android/intents
>https://tune.docs.branch.io/sdk/deep-linking-to-your-mobile-app-from-your-website/

Which states that:

>The functionality has changed slightly in Chrome for Android, versions 25 and later. It is no longer possible to launch an Android app by setting an iframe's src attribute. For example, navigating an iframe to a URI with a custom scheme such as paulsawesomeapp:// will not work even if the user has the appropriate app installed. Instead, you should implement a user gesture to launch the app via a custom scheme, or use the “intent:” syntax described in this article.
>https://developer.chrome.com/multidevice/android/intents

**Comment by jakubgs** [comment] 2020-03-18 11:10
Here is how the syntax looks like:
```
intent:
   HOST/URI-path // Optional host
   #Intent;
      package=[string];
      action=[string];
      category=[string];
      component=[string];
      scheme=[string];
   end;
```
An example would be:
```
intent:
   //scan/
   #Intent;
      package=com.google.zxing.client.android;
      scheme=zxing;
   end;
```
And in the form of an HTML tag:
```html
  <a href="intent://scan/#Intent;scheme=zxing;package=com.google.zxing.client.android;end">Button</a>
```

**Comment by jakubgs** [comment] 2020-03-18 11:15
I tried this:
```js
window.location.replace('intent://user/bridge#Intent;scheme=status-im;package=im.status.ethereum;end;')
```
But it doesn't seem to have any effect.

**Comment by jakubgs** [comment] 2020-03-18 11:49
Here is our definition of the Intent Filter:
```xml
<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="status-im" />
    <data android:scheme="ethereum" />
</intent-filter>
```
https://github.com/status-im/status-react/blob/c2890c47a6c58e217af703e5b26858b4a9ffcd71/android/app/src/main/AndroidManifest.xml#L65-L71

**Comment by jakubgs** [comment] 2020-03-18 11:56
Oh, interesting. I enabled JS console warnings and saw this:
![android_intent_filter_nav_blocked](https://user-images.githubusercontent.com/2212681/76958325-cfd18300-6917-11ea-8936-97328f5c7f14.png)
Which is progress of a kind.

**Comment by jakubgs** [comment] 2020-03-18 12:08
According to this:

>The policy on the Chrome side for triggering redirects to an app, whether through a custom scheme or an https App Link, is that this action must be triggered by the user, not Javascript. I believe the intention here is to prevent user surprise where a site opens an application without their explicit "consent" in the form of clicking on a link.
>https://stackoverflow.com/a/41882732

**Comment by jakubgs** [comment] 2020-03-18 12:38
I tried adding a `/redirect/*` endpoint to get around this:
```js
router.get('/redirect/:url(*)', (req, res) => res.redirect(req.params.url))
```
But all it does is it takes me to:
https://play.google.com/store/apps/details?id=im.status.ethereum
Which makes no sense.

**Comment by jakubgs** [comment] 2020-03-18 12:45
The thing is, this works just fine in Firefox Android browser.
I can just do:
```js
window.location = 'status-im://user/jakubgs`
```
And it opens the profile in Status app just fine after the timeout.

**Comment by jakubgs** [comment] 2020-03-18 12:50
Interesting. Using `market://` works in Chrome but does not in Brave.

**Comment by jakubgs** [comment] 2020-03-18 12:58
@jarradh so here's what I currently know:

* I can redirect to Play Store with referrers using JS just fine after `N` seconds, already implemented
* I cannot first try to redirect user to installed Status app in Chrome/Brave with JS timeout script
* If I redirect to Play Store after `N` seconds for user that has Status installed that makes no sense

Questions:

* Are we fine with redirecting to Play Store after `N` seconds even if user already has app installed?
* Or would it make more sense to have two buttons for user:
  - `Open in Status` that will work if app is installed, and do nothing if not
  - `Download Status` will redirect to play store with appropriate referrers

Toughts?

**Comment by jakubgs** [comment] 2020-03-18 13:07
This appears to be a known issue:
* https://bugs.chromium.org/p/chromium/issues/detail?id=738724
* https://github.com/openid/AppAuth-Android/issues/324
* https://github.com/EddyVerbruggen/Custom-URL-scheme/issues/156
* https://stackoverflow.com/questions/46727850/navigation-is-blocked-error-in-chrome-61-on-android

**Comment by jarradh** [comment] 2020-03-19 06:03
> The out field should contain exactly what is the path after / in the URL.
> The invite will be set by the Status app when generating the URL, and is based on user key.
> The cid will be also set by Status app but will be less dynamic than invite

`out` - correct
`invite` correct, it is based on the signature of a signed message used for registration
`cid` no this is not set by app, and will be MORE dynamic than invite

All 3 parameters should be treated as unique per request.

> It seems like it might be a problem. Because this link:
https://play.app.goo.gl/?link=https://play.google.com/store/apps/details?id=im.status.ethereum&referrer=out%3Djakubgs.eth%26invite%3Df79989f679386be7aa56dc1c4%26cid%3Dfoo

At first glance it looks like this is because the link property is not urlencoded, shouldn't it be 
https://play.app.goo.gl/?link=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dim.status.ethereum%26referrer%3Dout%253Djakubgs.eth%2526invite%253Df79989f679386be7aa56dc1c4%2526cid%253Dfoo

> Are we fine with redirecting to Play Store after N seconds even if user already has app installed?
In an ideal world, if the app is installed, it should handle the urls directly.

> would it make more sense to have two buttons for user
the less friction we can produce, the better.

**Comment by jakubgs** [comment] 2020-03-19 10:00
@jarradh okay, so I see to options here:

* Keep the button as `Open in Status` and trigger Play Store redirect after `N` seconds
* Keep the button as `Open in Status` but it would trigger JS that would:
  - Try deep link redirect to `status-im://whatever`
  - After 1-2 seconds redirect to PlayStore

Which one makes more sense to you? I think the second is sensible, but then I guess we don't do the redirect to Play Store without user interaction. Or do you want both?

**Comment by jarradh** [comment] 2020-03-19 15:16
Second Option for sure

**Comment by jakubgs** [comment] 2020-03-19 15:37
Based on conversation with Jarrad I'm going with the second option.

**Comment by jakubgs** [comment] 2020-03-19 17:03
I've finished the changes in https://github.com/status-im/universal-links-handler/pull/33.

You can test them by checking out the branch and doing `yarn install && yarn start` and going to `https://${YOUR_IP}:3000/` on your mobile device. You might have to open firewall for port `3000`.

**Comment by Serhy** [comment] 2020-03-19 18:01
Can't set it up. Something is not right.
```
$ yarn install && yarn start
yarn install v1.22.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.29s.
yarn run v1.22.0
$ node ./bin/www
GET / 302 88 - 11.305 ms

```
This 302 to `https://status.im/get/` I'm getting when load `http://192.168.1.140:3000/` in desktop. On mobile device in the same WiFi network it gives me `This site can't b reached ERR_CONNECTION_ABORTED` :(

**Comment by jakubgs** [comment] 2020-03-19 18:18
The fact that `/` redirects to https://status.im/get/ is exactly how it should behave. What you need is one of the implemented deep links like:

http://192.168.1.140:3000/user/jakubgs.eth
http://192.168.1.140:3000/chat/public/movies
http://192.168.1.140:3000/b/ens.domains

And for it to work for your mobile device you might have to open the `3000` port on the firewall.

**Comment by Serhy** [comment] 2020-03-19 20:51
Yea, firewall was disabled at that time. 
It was wifi router. All fine with another wifi. 

So as expected `http://192.168.31.146:3000/chat/public/movies` opens `Open in Status` page. 
With Androids (8th / 9th) it triggers deep link (so if Status installed opens deep link in Status and nothing happens when no Status on device) and in any case navigates to Status's PlayStore page. 
With iOS: opens Status by the deep link and opens Status page in AppStore if no Status installed. 

`Open in Status` button redirects to `https://status.im` page if `http://192.168.31.145:3000/chat/public/movies` opened in Safari on iOS (maybe better to use `else if (_userAgentHas('iPhone'))`?)

**Comment by jakubgs** [comment] 2020-03-19 20:59
Good point, using `iphone` to match user agent makes more sense based on this list:
https://developers.whatismybrowser.com/useragents/explore/operating_platform/iphone/8
Changed it in the PR. Thanks.

**Comment by jakubgs** [comment] 2020-03-19 22:49
Can you confirm though that on iPhone it opens only Status if it's installed? Because when I tried that on my phone it opened both Status and then the App Store, hiding Status in the background.

I can try using this trick to detect that the browser was put into background after opening the App:
```js
var siteLostFocus = false;
document.addEventListener("visibilitychange", (ev) => { siteLostFocus = true; });
```
To avoid opening the store afterwards the deep link has worked correctly.

**Comment by churik** [comment] 2020-03-20 10:23
@jakubgs 
> Can you confirm though that on iPhone it opens only Status if it's installed? Because when I tried that on my phone it opened both Status and then the App Store, hiding Status in the background.

No, for me it opens only Status.

## Questions / issues: 

#### 1) If I go back to web view and tap on "Open" in popup second time -> app store is opened.
(probably it is case that you described in https://github.com/status-im/universal-links-handler/issues/31#issuecomment-601452406)
![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/4557972/77150898-27e1c400-6a95-11ea-9150-05f968af604c.gif)
Also can be reproducible if browse several URLs -> tap on "Open in Status"several times  in a row
**Platform:** IOS
**Browser:** Safari
#### 2) Same happening if for some reason redirect to Status from Status itself doesn't work.
After several seconds instead of Status user is redirected to app store (I believe it is an issue on react side)

**Steps**:
- open http://192.168.1.140:3000/user/0x042e0309b5f6bedee93a1b984af08f89a101aff62d01ddd0a1c8f4a1d4db3b91e648c914019d09de9f07ddbaacb77fdf07e89b5e0d60e9a8df05b75f213661fcad in Status webview
- choose "Open in Status"
- wait 3 sec

**Expected result:**
will be redirected to user profile (issue on react-side)

**Actual result:**
redirected to app store 
**Platform:** IOS
**Browser:** Status webview

#### 3) "Safari cannot open the page because the address is invalid" warning - is it expected?
It is shown at attempt to tap on "Open in Status" when status not installed

**Platform:** IOS
**Browser:** Safari

#### 4) "UNKNOWN_URL_SCHEME" error is shown for several seconds until redirection in Status Webview 
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/4557972/77154186-8316b500-6a9b-11ea-865d-508caae9e53c.gif)

**Steps:**
- open http://192.168.1.140:3000/user/jakubgs.ethw
- tap on "Open in Status"
- choose "Open in Status"

**Expected result:**
redirected without errorrs
**Actual result:**
"UNKNOWN_URL_SCHEME" error is shown and after that user has been redirected
**Platform:** Android
**Browser:** Status webview


## Tested: 
### on IOS 12 (IPhone 7):
1.1. URL opened in - telegram webview, Status webview, Safari -  with  Status installed

- http://192.168.1.140:3000/user/jakubgs.eth (user profile is shown after login)
- http://192.168.1.140:3000/chat/public/movies (user joins public chat, however no redirect to public chat itself - should be fixed on status-react side)
- http://192.168.1.140:3000/b/ens.domains (no redirect after login, deep link is not working - should be fixed on status-react side)
- http://192.168.1.140:3000/browse/simpledapp.eth - invalid URL for now?
-http://192.168.1.140:3000/user/0x042e0309b5f6bedee93a1b984af08f89a101aff62d01ddd0a1c8f4a1d4db3b91e648c914019d09de9f07ddbaacb77fdf07e89b5e0d60e9a8df05b75f213661fcad (profile should be opened, resolver is working as expected; no redirect after login, deep link is not working - should be fixed on status-react side)
- http://192.168.1.140:3000/user/tanyatest1 (user profile is shown after login)

1.2. URL opened in - telegram webview, Safari with Status not installed -  in all cases I've been redirected to app store.

### on android 10(Xiaomi Mi Note9):
2.1. URL opened in - Android webview, Status webview with Status installed - in all cases was redirected to Status
2.2.URL opened in - Chrome with Status not installed -  - in all cases I've been redirected to Play store.

If you can guide me how can I help in testing parameters itself ( `out`, `invite`, `cid`) and if it is possible for now - it would be awesome.

**Comment by jakubgs** [comment] 2020-03-20 12:55
Thanks for all that work, appreciate it.

## Issues

#### If I go back to web view and tap on "Open" in popup second time -> app store is opened.

I've included a fix for that using the `visibilitychange` event like I described above.
The delay for opening the store is 3 seconds, which should be enough for browser to trigger `visibilitychange` and for `siteLostFocus` to be changed to `true` and blocking the store redirect.

#### Same happening if for some reason redirect to Status from Status itself doesn't work

This is an issue only because you're using an IP +port like `192.168.1.140:3000`. If the link was using the `join.status.im` domain the deep link should work just fine in Status app.

#### "UNKNOWN_URL_SCHEME" error is shown for several seconds until redirection in Status

This is only an issue because you're using the IP. As above if the domain was `join.status.im` it would have worked without opening the browser at all.

#### "Safari cannot open the page because the address is invalid" warning - is it expected?

I don't think we can avoid the `address is invalid` error when app is not installed on iPhone.
We just have to redirect quickly to App Store to let the user install it.

## Conclustion

I think it's ready.

**Comment by jakubgs** [comment] 2020-03-20 13:00
And I don't think there's a a way to test the url args - `out`, `invite`, `cid` - currently, other than verifying that they are in the URL after redirecting to PlayStore. There's nothing implemented yet to use them.

**Comment by jakubgs** [comment] 2020-03-20 13:49
@churik I've deployed the current state of #33 to https://join.status.im/ and I've tested most use cases. The only issue remaining is the `address is invalid` that shows up for a moment before the redirect to App Store in iPhone if the app is not installed. I don't know of a way to fix this currently.

**Comment by Serhy** [comment] 2020-03-20 14:57
Yes, that's only issue I see from `https://join.status.im/ `. However it's better than with what we supposed to go for Android (when Status installed and we open app and then redirect to PlayStore which would much more users would experience)

**Closed** 2020-03-20 15:05 UTC
